[package]
name = "makair-control"
version = "1.6.0"
description = "Control UI for the MakAir SARS respirator."
readme = "README.md"
license-file = "LICENSE.md"
edition = "2018"
homepage = "https://github.com/makers-for-life/makair"
repository = "https://github.com/makers-for-life/makair.git"
keywords = ["covid-19", "fusion-360", "cad", "covid", "coronavirus", "sars-cov-2", "nucleo-board", "covid-respirator", "makair-respirators", "medical", "ards"]
categories = ["gui", "hardware-support"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>", "Quentin Adam <quentin.adam@waxzce.org>", "David Sferruzza <david.sferruzza@gmail.com>"]

[[bin]]
name = "makair-control"
path = "src/main.rs"
doc = false

[dependencies]
log = "0.4"
clap = { version = "2.33", default-features = false }
lazy_static = "1.4"
rust-embed = { version = "5.5.1", features = ["compression"] }
chrono = "0.4.11"
fluent = "0.12"
unic-langid = "0.9"
inflate = "0.4"
winit = "0.19"
image = "0.23.3"
glium = "0.24"
plotters = {version = "0.2.12", default_features = false, features = ["image_encoder", "chrono", "line_series", "palette", "ttf"]}
conrod_glium = "0.69"
conrod_winit = "0.69"
conrod_core = "0.69"
sysfs_gpio = { version = "0.5", optional = true }
rn2903 = { git = "https://github.com/waxzce/lora-rust-rn2903-rn2483.git", rev = "b086057ba096920abef3870ad0cefa2c80a343e2", optional = true }
makair-telemetry = { git = "https://github.com/makers-for-life/makair-telemetry", features = ["env_logger"], rev = "d073a91a776ce40db13ed516117f3f86c0c357b1" }

[features]
default = []
graph-scaler = []
lora = ["rn2903", "sysfs_gpio"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
